using System.Text;
using VeloORM.Migrations.Schema;
using VeloORM.Sql;

namespace VeloORM.Migrations;

/// <summary>Renders <see cref="MigrationOperation"/>s into PostgreSQL DDL statements.</summary>
public sealed class PostgresMigrationSqlGenerator
{
    private readonly ISqlDialect _dialect;

    public PostgresMigrationSqlGenerator(ISqlDialect dialect) => _dialect = dialect;

    public string Generate(IEnumerable<MigrationOperation> operations)
    {
        var sb = new StringBuilder();
        foreach (var op in operations)
        {
            AppendOperation(sb, op);
            sb.AppendLine();
        }
        return sb.ToString();
    }

    private void AppendOperation(StringBuilder sb, MigrationOperation op)
    {
        switch (op)
        {
            case CreateTableOperation create:
                AppendCreateTable(sb, create.Table);
                break;
            case DropTableOperation drop:
                sb.Append("DROP TABLE ").Append(QName(drop.Schema, drop.Name)).Append(';');
                break;
            case AddColumnOperation add:
                sb.Append("ALTER TABLE ").Append(QName(add.Schema, add.Table))
                  .Append(" ADD COLUMN ").Append(ColumnDefinition(add.Column)).Append(';');
                break;
            case DropColumnOperation dropCol:
                sb.Append("ALTER TABLE ").Append(QName(dropCol.Schema, dropCol.Table))
                  .Append(" DROP COLUMN ").Append(_dialect.QuoteIdentifier(dropCol.Column)).Append(';');
                break;
            case AlterColumnOperation alter:
                var col = _dialect.QuoteIdentifier(alter.Target.Name);
                var tbl = QName(alter.Schema, alter.Table);
                sb.Append("ALTER TABLE ").Append(tbl).Append(" ALTER COLUMN ").Append(col)
                  .Append(" TYPE ").Append(alter.Target.StoreType)
                  .Append(" USING ").Append(col).Append("::").Append(alter.Target.StoreType).Append(';').AppendLine();
                sb.Append("ALTER TABLE ").Append(tbl).Append(" ALTER COLUMN ").Append(col)
                  .Append(alter.Target.IsNullable ? " DROP NOT NULL" : " SET NOT NULL").Append(';');
                break;
            case CreateIndexOperation createIx:
                sb.Append("CREATE ").Append(createIx.Index.IsUnique ? "UNIQUE " : "")
                  .Append("INDEX ").Append(_dialect.QuoteIdentifier(createIx.Index.Name))
                  .Append(" ON ").Append(QName(createIx.Schema, createIx.Table))
                  .Append(" (")
                  .Append(string.Join(", ", createIx.Index.Columns.Select(_dialect.QuoteIdentifier)))
                  .Append(");");
                break;
            case DropIndexOperation dropIx:
                sb.Append("DROP INDEX ").Append(QName(dropIx.Schema, dropIx.IndexName)).Append(';');
                break;
            case AddForeignKeyOperation addFk:
                var fk = addFk.ForeignKey;
                sb.Append("ALTER TABLE ").Append(QName(addFk.Schema, addFk.Table))
                  .Append(" ADD CONSTRAINT ").Append(_dialect.QuoteIdentifier(fk.Name))
                  .Append(" FOREIGN KEY (")
                  .Append(string.Join(", ", fk.Columns.Select(_dialect.QuoteIdentifier)))
                  .Append(") REFERENCES ").Append(QName(fk.PrincipalSchema, fk.PrincipalTable))
                  .Append(" (")
                  .Append(string.Join(", ", fk.PrincipalColumns.Select(_dialect.QuoteIdentifier)))
                  .Append(");");
                break;
            case DropForeignKeyOperation dropFk:
                sb.Append("ALTER TABLE ").Append(QName(dropFk.Schema, dropFk.Table))
                  .Append(" DROP CONSTRAINT ").Append(_dialect.QuoteIdentifier(dropFk.Name)).Append(';');
                break;
            default:
                throw new NotSupportedException($"Operation '{op.GetType().Name}' is not supported.");
        }
    }

    private void AppendCreateTable(StringBuilder sb, SchemaTable table)
    {
        sb.Append("CREATE TABLE ").Append(QName(table.Schema, table.Name)).Append(" (").AppendLine();
        for (int i = 0; i < table.Columns.Count; i++)
        {
            sb.Append("    ").Append(ColumnDefinition(table.Columns[i]));
            if (i < table.Columns.Count - 1 || table.PrimaryKey.Count > 0) sb.Append(',');
            sb.AppendLine();
        }
        if (table.PrimaryKey.Count > 0)
        {
            sb.Append("    PRIMARY KEY (")
              .Append(string.Join(", ", table.PrimaryKey.Select(_dialect.QuoteIdentifier)))
              .Append(')').AppendLine();
        }
        sb.Append(");");
    }

    private string ColumnDefinition(SchemaColumn column)
    {
        var sb = new StringBuilder();
        sb.Append(_dialect.QuoteIdentifier(column.Name)).Append(' ').Append(column.StoreType);
        if (column.IsIdentity)
            sb.Append(" GENERATED BY DEFAULT AS IDENTITY");
        else if (!column.IsNullable)
            sb.Append(" NOT NULL");
        return sb.ToString();
    }

    private string QName(string? schema, string name) => _dialect.QuoteQualifiedName(schema, name);
}
