using VeloORM.Metadata;

namespace VeloORM.Tests.Unit;

public class MetadataTests
{
    private static EntityModel Build<T>(Action<ModelBuilder>? configure = null)
    {
        var model = VeloModel.Build([typeof(T)], configure);
        return model.GetEntity<T>();
    }

    [Fact]
    public void ConventionDefaults_SnakeCase_Pluralized_Table_And_Columns()
    {
        var e = Build<User>();

        Assert.Equal("users", e.TableName);
        Assert.Null(e.Schema);
        Assert.Equal("id", e.GetColumnByProperty("Id").ColumnName);
        Assert.Equal("login_count", e.GetColumnByProperty("LoginCount").ColumnName);
        Assert.Equal("created_at", e.GetColumnByProperty("CreatedAt").ColumnName);
    }

    [Fact]
    public void ConventionKey_Id_IsPrimaryKey_And_StoreGeneratedOnAdd()
    {
        var e = Build<User>();

        Assert.True(e.HasKey);
        Assert.Single(e.KeyColumns);
        var key = e.KeyColumns[0];
        Assert.Equal("Id", key.PropertyName);
        Assert.True(key.IsKey);
        Assert.False(key.IsNullable);
        Assert.Equal(StoreGenerated.OnAdd, key.StoreGenerated);
    }

    [Fact]
    public void Nullability_FollowsNrt_And_ValueTypes()
    {
        var e = Build<User>();

        Assert.False(e.GetColumnByProperty("Name").IsNullable);    // non-null string
        Assert.True(e.GetColumnByProperty("Email").IsNullable);    // string?
        Assert.False(e.GetColumnByProperty("LoginCount").IsNullable); // int
    }

    [Fact]
    public void TableAttribute_Sets_Name_And_Schema()
    {
        var e = Build<Person>();
        Assert.Equal("people", e.TableName);
        Assert.Equal("app", e.Schema);
    }

    [Fact]
    public void KeyAttribute_On_NonId_Property_Is_Honored()
    {
        var e = Build<Person>();
        Assert.Single(e.KeyColumns);
        Assert.Equal("PersonKey", e.KeyColumns[0].PropertyName);
        // Guid key is not an integer => not store-generated by convention.
        Assert.Equal(StoreGenerated.Never, e.KeyColumns[0].StoreGenerated);
    }

    [Fact]
    public void ColumnAttribute_Sets_Name_And_StoreType()
    {
        var e = Build<Person>();
        var col = e.GetColumnByProperty("FullName");
        Assert.Equal("full_name", col.ColumnName);
        Assert.Equal("varchar(200)", col.StoreType);
    }

    [Fact]
    public void NotMapped_And_Navigation_Properties_Are_Excluded()
    {
        var e = Build<Person>();
        Assert.Null(e.FindColumnByProperty("ComputedDisplay")); // [NotMapped]
        Assert.Null(e.FindColumnByProperty("Friends"));         // navigation (non-scalar)
    }

    [Fact]
    public void IndexAttribute_Is_Materialized_As_Unique_Index()
    {
        var e = Build<Person>();
        var ix = Assert.Single(e.Indexes);
        Assert.True(ix.IsUnique);
        Assert.Equal("national_id", Assert.Single(ix.Columns).ColumnName);
    }

    [Fact]
    public void Fluent_Overrides_Win_Over_Convention()
    {
        var e = Build<OrderLine>(mb =>
        {
            mb.Entity<OrderLine>()
              .ToTable("order_lines", "sales")
              .HasKey(x => new { x.OrderId, x.LineNumber })
              .HasIndex(x => x.Amount, unique: false);
            mb.Entity<OrderLine>().Property(x => x.Note).HasColumnName("memo");
        });

        Assert.Equal("order_lines", e.TableName);
        Assert.Equal("sales", e.Schema);
        Assert.Equal(2, e.KeyColumns.Count);
        Assert.Equal("OrderId", e.KeyColumns[0].PropertyName);
        Assert.Equal("LineNumber", e.KeyColumns[1].PropertyName);
        Assert.Equal(0, e.KeyColumns[0].KeyOrder);
        Assert.Equal(1, e.KeyColumns[1].KeyOrder);
        Assert.Equal("memo", e.GetColumnByProperty("Note").ColumnName);
        Assert.Single(e.Indexes);
        Assert.False(e.Indexes[0].IsUnique);
    }

    [Fact]
    public void Fluent_Ignore_Excludes_Property()
    {
        var e = Build<User>(mb => mb.Entity<User>().Ignore(x => x.Email));
        Assert.Null(e.FindColumnByProperty("Email"));
    }
}
